### ISSUE TITLE
automatic compiling script missing in branch Qt

### ISSUE THREAD

**Issue by Artoria2e5** [RamseyX/RamseyX-client#5]
额，master那里有vcproj文件指引VS进行编译，但是Qt这边就坑爹了……
觉得make蛋疼的话用cmake好了，主要就是要写好各个lib和bin对应的源码……

**Comment by zizhengtai** [comment]
咦？Qt的话不是.vcproj=>.pro而且直接用qmake就可以很方便的生成makefile了吗？毕竟要手动编译的话Qt库是附带qmake的呀。

**Comment by Artoria2e5** [comment]
脑抽了。。
