### ISSUE TITLE
编译失败，来瞅瞅？

### ISSUE THREAD

**Issue by zhouxiaobo500** [RamseyX/RamseyX-client#7]
Makefile:1903: recipe for target 'accountdialog.o' failed
make: **\* [accountdialog.o] Error 1

**Comment by zizhengtai** [comment]
您是按照README.md的内容编译的吗？README.md的INSTALL部分我自己还没验证过，不知道可不可行。

**Comment by zhouxiaobo500** [comment]
是的，按照README.MD编译，以下是details：
[zhou@Arch_Mo11n rx]$ cd RamseyX && git checkout Qt &&
qmake && make && sudo make install

<hr>

已经位于 'Qt'
您的分支与上游分支 'origin/Qt' 一致。
g++ -c -pipe -std=c++11 -Wall -Wextra -pedantic -march=x86-64 -mtune=generic -pipe -fstack-protector --param=ssp-buffer-size=4 -O3 -flto -Wall -W -D_REENTRANT -fPIE -DRX_QT -DAPP_VERSION=\"5.0.3\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I. -IC:/Dev/Libraries/curl-7.35.0_msvc2013_x86/builds/libcurl-vc12-x86-release-dll-ipv6-sspi-spnego-winssl/include -IC:/Dev/Libraries/boost_1_55_0 -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -o accountdialog.o accountdialog.cpp
In file included from ramseyxcontroller.h:24:0,
                 from accountdialog.h:26,
                 from accountdialog.cpp:21:
ramseyxtask.h:54:5: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     std::atomic<bool> useFlag{false};
     ^
ramseyxtask.h:54:37: 警告：多余的‘;’ [-Wpedantic]
     std::atomic<bool> useFlag{false};
                                     ^
ramseyxtask.h:55:5: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     std::atomic<bool> termFlag{false};
     ^
ramseyxtask.h:55:38: 警告：多余的‘;’ [-Wpedantic]
     std::atomic<bool> termFlag{false};
                                      ^
In file included from accountdialog.h:26:0,
                 from accountdialog.cpp:21:
ramseyxcontroller.h:72:5: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     std::atomic<unsigned int> threadCounter{0};
     ^
ramseyxcontroller.h:72:47: 警告：多余的‘;’ [-Wpedantic]
     std::atomic<unsigned int> threadCounter{0};
                                               ^
ramseyxcontroller.h:74:5: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     std::atomic<bool> running{false};
     ^
ramseyxcontroller.h:74:37: 警告：多余的‘;’ [-Wpedantic]
     std::atomic<bool> running{false};
                                     ^
ramseyxcontroller.h:77:13: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     mutable std::atomicstd::time_t lastLog{0};
             ^
ramseyxcontroller.h:77:48: 警告：多余的‘;’ [-Wpedantic]
     mutable std::atomicstd::time_t lastLog{0};
                                                ^
ramseyxcontroller.h:78:5: **错误：‘atomic’不是命名空间‘std’中的一个类型名**
     std::atomicstd::time_t time{0};
     ^
ramseyxcontroller.h:78:37: 警告：多余的‘;’ [-Wpedantic]
     std::atomicstd::time_t time{0};
                                     ^
Makefile:1903: recipe for target 'accountdialog.o' failed
make: **\* [accountdialog.o] Error 1

**Comment by zizhengtai** [comment]
是这样，因为gcc对std::atomic库的实现不完全，所以如果用gcc编译的话需要链接boost::atomic库。boost库的路径请在RamseyX.pro里的gcc子项里设定，关于boost::atomic库的编译请参见boost手册。

**Comment by zhouxiaobo500** [comment]
文档表示看不懂。。
是要更改 RamseyX.pro Line 91的 $$BOOST_DIR 吗？

**Comment by Artoria2e5** [comment]
嗯，看上去我需要让qmake获得自己找boost的能力。。。

@Trickness 有空的话请协助…

以及，ZizhengTai也许你需要在collaborator列表里面加几个人。

Arthur Wang from equn.com

**Comment by Artoria2e5** [comment]
另外就是依赖要列出来。。

目前已知
1. Boost
2. curl

**Comment by zizhengtai** [comment]
@zhouxiaobo500  嗯，目前需要手动设置。gcc的话就在:
gcc {
    ...
}
这一块里设定。

@Arthur200000 好的，谢谢提醒。另外，collaborator那个是加到哪里呢？

**Comment by Artoria2e5** [comment]
@ZizhengTai 
https://github.com/ZizhengTai/RamseyX/settings/collaboration 
就这样

**Comment by Artoria2e5** [comment]
尝试修改pro文件以便使程序做到平台独立。。

**Comment by zizhengtai** [comment]
@Arthur200000 pro文件现在已经是平台独立的了，只是外部库路径需要手动指定。考虑把README.md的INSTALL部分修改一下放到后面去吧，和git clone那块儿放到一起。毕竟一般用户不会手动编译。

**Comment by Artoria2e5** [comment]
驳回。

需要修改的pro不是好pro。

必须有自动检测机制。。

**Comment by Artoria2e5** [comment]
以及，gh本来就是geek的地方，install就该放前面。。

**Comment by zizhengtai** [comment]
这个README一定程度上是给所有用户看的，大部分人会走官网而不是gh，我觉得大概不能预计他们都是geek。毕竟你想他们下载下来binaries之后打开README一看发现还要INSTALL可能会很迷惑的...而且严格来说COMPILE也不同等与INSTALL吧，INSTALL包括COMPILE和INTEGRATE的过程。

pro文件的话你有什么好想法吗？我也觉得现在这样不太方便。难道要写个configure或者脚本什么的...

2014-04-10 16:04 GMT+08:00 Arthur Wang notifications@github.com:

**Comment by zizhengtai** [comment]
普通用户的体验我认为要放到第一位。其实BOINC的面板我觉得就是用户不友好体验的典范...当然我们geeks会觉得如此这般很炫酷不过一般人就头大了

**Comment by Artoria2e5** [comment]
这不是问题。github项目的wiki是额外的包括但不限于用户指南的好去处。

**Comment by Artoria2e5** [comment]
install那边几乎是所有开源项目的普遍习惯。。233

需要手册的话那也不是readme的事情了。

**Comment by Artoria2e5** [comment]
另外，这边的README是源码README，客户端手册要另写。

走版本库wiki，或者ramseyx.org 或者equn wiki或者ZizhengTai.github.io

**Comment by Artoria2e5** [comment]
那啥，我先去创建一个RamseyX的group。。。

然后把你丢进owner你再把这个repo给transfer ownership到RamseyX。。

**Comment by zizhengtai** [comment]
@Arthur200000 Done

**Comment by Artoria2e5** [comment]
请再次尝试编译！

**Comment by zizhengtai** [comment]
@Arthur200000 你测试过README.md里的INSTALL吗？

**Comment by Artoria2e5** [comment]
not yet，刷作业中。。。。

我估计现在这个会好很多。

**Comment by zizhengtai** [comment]
加油。不过以后做出任何commit之前最好都先确认切实可行。INSTALL那块儿我近期会着手改进，有不少东西要说明。pro文件我也会进一步调整和注释。有空的时候欢迎帮忙
:)

2014-04-10 18:40 GMT+08:00 Arthur Wang notifications@github.com:

**Comment by Artoria2e5** [comment]
这方面我管的比较松，一般就是做到不会break别的东西就好了。。。。。

**Comment by zizhengtai** [comment]
如果没有测试的条件，最好在comment里注明untested，这样其他开发者可以帮忙测试:)

Arthur Wang notifications@github.com于2014年4月10日星期四写道：

**Comment by zizhengtai** [comment]
或者branch出去，测试之后再pull回来。

Arthur Wang notifications@github.com于2014年4月10日星期四写道：

**Comment by Artoria2e5** [comment]
还有一件事。。。

在这货的跨平台稳定下来之前。。。也许你会看到各种鼓动编译者做hack的注释。。。。

嗯，我是深井冰233

**Comment by Artoria2e5** [comment]
可以接受，在遇到高危操作的时候我会做，这次的情况。。。。不能保证不会忘

**Comment by Artoria2e5** [comment]
untested我应该都能做到。。

**Comment by Artoria2e5** [comment]
测试编译通过了吗？

**Comment by zhouxiaobo500** [comment]
of course。。
这份代码在发给Tai Zizhen之前debug了好几次，应该没问题。

**Comment by Artoria2e5** [comment]
。。。。。我说的是现在那个.pro啊！

**Comment by zhouxiaobo500** [comment]
。。。let me see。

**Comment by zhouxiaobo500** [comment]
1)

<pre>git clone https://github.com/RamseyX/RamseyX.git
</pre>

这行的执行结果为：

<pre>fatal: 不能为 'RamseyX' 创建工作区目录。: 没有那个文件或目录</pre>

应该改为：

<pre>git clone https://github.com/ZizhengTai/RamseyX.git</pre>

2) boost 的老问题还在，错误代码同上。
README.MD应该要包含怎么更改gcc配置什么的。。否则我们不会改啊。。

**Comment by Artoria2e5** [comment]
额，允许我问一句，你安装boost了吗。。。

请回复`find /usr -name libboost*`的结果。。。
2014-4-12 上午12:19于 "zhouxiaobo" notifications@github.com写道：

**Comment by Artoria2e5** [comment]
git目录不存在问题，若失败，使用RamseyX/RamseyX.git.

请尝试删除原源码目录。

**Comment by zhouxiaobo500** [comment]
find 命令结果：
`
/usr/lib/libboost_graph_parallel.so.1.55.0
/usr/lib/libboost_math_tr1.a
/usr/lib/libboost_atomic.so
/usr/lib/libboost_context.a
/usr/lib/libboost_math_tr1l.a
/usr/lib/libboost_unit_test_framework.a
/usr/lib/libboost_atomic.so.1.55.0
/usr/lib/libboost_test_exec_monitor.a
/usr/lib/libboost_chrono.a
/usr/lib/libboost_log.a
/usr/lib/libboost_math_tr1f.a
/usr/lib/libboost_mpi.a
/usr/lib/libboost_math_tr1.so.1.55.0
/usr/lib/libboost_log.so
/usr/lib/libboost_log.so.1.55.0
/usr/lib/libboost_math_c99.a
/usr/lib/libboost_context.so.1.55.0
/usr/lib/libboost_math_c99l.so.1.55.0
/usr/lib/libboost_filesystem.so
/usr/lib/libboost_coroutine.so
/usr/lib/libboost_python3.a
/usr/lib/libboost_random.so
/usr/lib/libboost_regex.so
/usr/lib/libboost_python3.so.1.55.0
/usr/lib/libboost_math_tr1f.so
/usr/lib/libboost_wave.a
/usr/lib/libboost_system.a
/usr/lib/libboost_locale.a
/usr/lib/libboost_graph_parallel.a
/usr/lib/libboost_filesystem.a
/usr/lib/libboost_graph.a
/usr/lib/libboost_math_c99.so
/usr/lib/libboost_wserialization.so
/usr/lib/libboost_wave.so
/usr/lib/libboost_math_tr1f.so.1.55.0
/usr/lib/libboost_thread.a
/usr/lib/libboost_python.a
/usr/lib/libboost_math_tr1.so
/usr/lib/libboost_python.so.1.55.0
/usr/lib/libboost_system.so
/usr/lib/libboost_math_tr1l.so.1.55.0
/usr/lib/libboost_log_setup.so
/usr/lib/libboost_filesystem.so.1.55.0
/usr/lib/libboost_context.so
/usr/lib/libboost_math_c99l.a
/usr/lib/libboost_math_c99.so.1.55.0
/usr/lib/libboost_python.so
/usr/lib/libboost_chrono.so
/usr/lib/libboost_program_options.so
/usr/lib/libboost_exception.a
/usr/lib/libboost_thread.so.1.55.0
/usr/lib/libboost_iostreams.so
/usr/lib/libboost_unit_test_framework.so.1.55.0
/usr/lib/libboost_date_time.so
/usr/lib/libboost_math_c99f.so.1.55.0
/usr/lib/libboost_wserialization.so.1.55.0
/usr/lib/libboost_mpi_python.so
/usr/lib/libboost_prg_exec_monitor.so
/usr/lib/libboost_mpi_python.a
/usr/lib/libboost_math_c99l.so
/usr/lib/libboost_thread.so
/usr/lib/libboost_prg_exec_monitor.a
/usr/lib/libboost_unit_test_framework.so
/usr/lib/libboost_serialization.so.1.55.0
/usr/lib/libboost_random.a
/usr/lib/libboost_prg_exec_monitor.so.1.55.0
/usr/lib/libboost_signals.a
/usr/lib/libboost_wserialization.a
/usr/lib/libboost_log_setup.a
/usr/lib/libboost_timer.so
/usr/lib/libboost_program_options.a
/usr/lib/libboost_locale.so
/usr/lib/libboost_graph_parallel.so
/usr/lib/libboost_iostreams.a
/usr/lib/libboost_iostreams.so.1.55.0
/usr/lib/libboost_graph.so.1.55.0
/usr/lib/libboost_locale.so.1.55.0
/usr/lib/libboost_signals.so
/usr/lib/libboost_regex.a
/usr/lib/libboost_program_options.so.1.55.0
/usr/lib/libboost_log_setup.so.1.55.0
/usr/lib/libboost_wave.so.1.55.0
/usr/lib/libboost_serialization.a
/usr/lib/libboost_timer.so.1.55.0
/usr/lib/libboost_timer.a
/usr/lib/libboost_math_c99f.so
/usr/lib/libboost_random.so.1.55.0
/usr/lib/libboost_chrono.so.1.55.0
/usr/lib/libboost_date_time.so.1.55.0
/usr/lib/libboost_serialization.so
/usr/lib/libboost_math_c99f.a
/usr/lib/libboost_atomic.a
/usr/lib/libboost_mpi.so
/usr/lib/libboost_graph.so
/usr/lib/libboost_math_tr1l.so
/usr/lib/libboost_python3.so
/usr/lib/libboost_system.so.1.55.0
/usr/lib/libboost_mpi.so.1.55.0
/usr/lib/libboost_signals.so.1.55.0
/usr/lib/libboost_coroutine.so.1.55.0
/usr/lib/libboost_mpi_python.so.1.55.0
/usr/lib/libboost_date_time.a
/usr/lib/libboost_regex.so.1.55.0
/usr/lib/libboost_coroutine.a
find: “/usr/share/polkit-1/rules.d”: 权限不够`
git目录重新试了下，没问题了。

**Comment by Artoria2e5** [comment]
啊咧。。。我记得我把/usr/lib纳入boost库目录了啊。。
发生什么了。。

**Comment by Artoria2e5** [comment]
啊擦。。atomic的确没加

**Comment by Artoria2e5** [comment]
那也不对，因为LIBS是共同的。。

**Comment by Artoria2e5** [comment]
抱歉。。。请在/usr里面找boost...
`find /usr -name *boost*`
原因是编译出错应该是include的问题才对。。

**Comment by Artoria2e5** [comment]
抱歉。。。请在/usr里面找boost...
`find /usr -name *boost*`
原因是编译出错应该是include的问题才对。。

**Comment by zhouxiaobo500** [comment]
Output：
`/usr/include/CLucene/ext/boost
/usr/include/boost
/usr/include/boost/chrono/typeof/boost
/usr/include/boost/fusion/include/boost_tuple.hpp
/usr/include/boost/fusion/include/boost_array.hpp
/usr/include/boost/fusion/adapted/boost_array
/usr/include/boost/fusion/adapted/boost_tuple
/usr/include/boost/fusion/adapted/boost_tuple/boost_tuple_iterator.hpp
/usr/include/boost/fusion/adapted/boost_tuple.hpp
/usr/include/boost/fusion/adapted/boost_array.hpp
/usr/include/boost/geometry/geometries/adapted/boost_tuple.hpp
/usr/include/boost/geometry/geometries/adapted/boost_array.hpp
/usr/include/boost/geometry/geometries/adapted/boost_polygon
/usr/include/boost/geometry/geometries/adapted/boost_polygon.hpp
/usr/include/boost/geometry/geometries/adapted/boost_fusion.hpp
/usr/include/boost/geometry/geometries/adapted/boost_range
/usr/include/boost/icl/detail/boost_config.hpp
/usr/include/c++/4.8.2/bits/boost_concept_check.h
/usr/lib/libboost_graph_parallel.so.1.55.0
/usr/lib/libboost_math_tr1.a
/usr/lib/libboost_atomic.so
/usr/lib/libboost_context.a
/usr/lib/libboost_math_tr1l.a
/usr/lib/libboost_unit_test_framework.a
/usr/lib/libboost_atomic.so.1.55.0
/usr/lib/libboost_test_exec_monitor.a
/usr/lib/libboost_chrono.a
/usr/lib/libboost_log.a
/usr/lib/libboost_math_tr1f.a
/usr/lib/libboost_mpi.a
/usr/lib/libboost_math_tr1.so.1.55.0
/usr/lib/libboost_log.so
/usr/lib/libboost_log.so.1.55.0
/usr/lib/libboost_math_c99.a
/usr/lib/libboost_context.so.1.55.0
/usr/lib/libboost_math_c99l.so.1.55.0
/usr/lib/libboost_filesystem.so
/usr/lib/libboost_coroutine.so
/usr/lib/libboost_python3.a
/usr/lib/libboost_random.so
/usr/lib/libboost_regex.so
/usr/lib/libboost_python3.so.1.55.0
/usr/lib/libboost_math_tr1f.so
/usr/lib/libboost_wave.a
/usr/lib/libboost_system.a
/usr/lib/libboost_locale.a
/usr/lib/libboost_graph_parallel.a
/usr/lib/libboost_filesystem.a
/usr/lib/libboost_graph.a
/usr/lib/libboost_math_c99.so
/usr/lib/libboost_wserialization.so
/usr/lib/libboost_wave.so
/usr/lib/libboost_math_tr1f.so.1.55.0
/usr/lib/libboost_thread.a
/usr/lib/libboost_python.a
/usr/lib/libboost_math_tr1.so
/usr/lib/libboost_python.so.1.55.0
/usr/lib/libboost_system.so
/usr/lib/libboost_math_tr1l.so.1.55.0
/usr/lib/libboost_log_setup.so
/usr/lib/libboost_filesystem.so.1.55.0
/usr/lib/libboost_context.so
/usr/lib/libboost_math_c99l.a
/usr/lib/libboost_math_c99.so.1.55.0
/usr/lib/libboost_python.so
/usr/lib/libboost_chrono.so
/usr/lib/libboost_program_options.so
/usr/lib/libboost_exception.a
/usr/lib/libboost_thread.so.1.55.0
/usr/lib/libboost_iostreams.so
/usr/lib/libboost_unit_test_framework.so.1.55.0
/usr/lib/libboost_date_time.so
/usr/lib/libboost_math_c99f.so.1.55.0
/usr/lib/libboost_wserialization.so.1.55.0
/usr/lib/libboost_mpi_python.so
/usr/lib/libboost_prg_exec_monitor.so
/usr/lib/libboost_mpi_python.a
/usr/lib/libboost_math_c99l.so
/usr/lib/libboost_thread.so
/usr/lib/libboost_prg_exec_monitor.a
/usr/lib/modules/3.13.8-1-ARCH/build/scripts/rt-tester/t5-l4-pi-boost-deboost.tst
/usr/lib/modules/3.13.8-1-ARCH/build/scripts/rt-tester/t5-l4-pi-boost-deboost-setsched.tst
/usr/lib/modules/3.13.8-1-ARCH/build/scripts/rt-tester/t4-l2-pi-deboost.tst
/usr/lib/libboost_unit_test_framework.so
/usr/lib/libboost_serialization.so.1.55.0
/usr/lib/libboost_random.a
/usr/lib/libboost_prg_exec_monitor.so.1.55.0
/usr/lib/libboost_signals.a
/usr/lib/libboost_wserialization.a
/usr/lib/libboost_log_setup.a
/usr/lib/libboost_timer.so
/usr/lib/libboost_program_options.a
/usr/lib/libboost_locale.so
/usr/lib/libboost_graph_parallel.so
/usr/lib/libboost_iostreams.a
/usr/lib/libboost_iostreams.so.1.55.0
/usr/lib/libboost_graph.so.1.55.0
/usr/lib/libboost_locale.so.1.55.0
/usr/lib/libboost_signals.so
/usr/lib/libboost_regex.a
/usr/lib/libboost_program_options.so.1.55.0
/usr/lib/libboost_log_setup.so.1.55.0
/usr/lib/libboost_wave.so.1.55.0
/usr/lib/libboost_serialization.a
/usr/lib/libboost_timer.so.1.55.0
/usr/lib/libboost_timer.a
/usr/lib/libboost_math_c99f.so
/usr/lib/libboost_random.so.1.55.0
/usr/lib/libboost_chrono.so.1.55.0
/usr/lib/libboost_date_time.so.1.55.0
/usr/lib/libboost_serialization.so
/usr/lib/libboost_math_c99f.a
/usr/lib/libboost_atomic.a
/usr/lib/libboost_mpi.so
/usr/lib/libboost_graph.so
/usr/lib/libboost_math_tr1l.so
/usr/lib/libboost_python3.so
/usr/lib/libboost_system.so.1.55.0
/usr/lib/libboost_mpi.so.1.55.0
/usr/lib/libboost_signals.so.1.55.0
/usr/lib/libboost_coroutine.so.1.55.0
/usr/lib/libboost_mpi_python.so.1.55.0
/usr/lib/libboost_date_time.a
/usr/lib/libboost_regex.so.1.55.0
/usr/lib/libboost_coroutine.a
/usr/share/licenses/boost-libs
/usr/share/licenses/boost
/usr/share/boostbook
/usr/share/boostbook/xsl/doxygen/doxygen2boostbook.xsl
/usr/share/boostbook/xsl/dtd/dtd2boostbook.xsl
/usr/share/boostbook/dtd/boostbook.dtd
/usr/share/boostbook/dtd/1.1/boostbook.dtd
/usr/share/boostbook/dtd/1.1/boost-no-inspect
/usr/share/qt4/mkspecs/features/symbian/symbian_appbooster.prf
/usr/share/qtcreator/debugger/boosttypes.py`

**Comment by Artoria2e5** [comment]
我实在不知道怎么了。。
@ZizhengTai @Trickness
目前的建议是cd进RamseyX，进行make clean，然后git pull，接着再来qmake那一套。

**Comment by zizhengtai** [comment]
库的链接还要制定具体的库文件，就是.a那个。在不同的系统下用不同编译器生成的库文件命名规则不一样，而且不相互兼容。请在pro文件中修改LIBS
= -lnameOfLibFile部分以指定库文件，其中nameOfLibFile是libxxx.a文件的全名去掉lib前缀和.a后缀。如果编译器不同的话，链接也不一定会成功，不过在linux下应该都是gcc。

Arthur Wang notifications@github.com于2014年4月16日星期三写道：

**Comment by zizhengtai** [comment]
LIBS += -L库目录 -l库文件。这里应该用LIBS += -L/usr/lib -lboost_atomic

**Comment by zizhengtai** [comment]
另外libcurl的配置也要以此类推。编译的时候请先在各lib, include目录中寻找对应的头文件和库文件。另外 @Arthur200000 不要把这个issue标成bug吧，这个只是配置问题。

**Comment by zizhengtai** [comment]
@Arthur200000 如果我没想错make install应该是不可行的吧？install部分我们有提供吗？另外，我觉得还是用IDE构建比较好...Qt不好配置。

**Comment by Artoria2e5** [comment]
额。。。uh-oh
2014-4-16 下午9:24于 "Zizheng Tai" notifications@github.com写道：

**Comment by Artoria2e5** [comment]
IDE提供构建最后还是Qt的事情。。

搞清IDE怎么干的很重要，另外Qt Designer实际调用的**就是**qmake。
2014-4-16 下午9:24于 "Zizheng Tai" notifications@github.com写道：

**Comment by zizhengtai** [comment]
我知道就是qmake，但搞清楚怎么编译是开发者的事情，这样这么用户真的好么。。不赞同。

Arthur Wang notifications@github.com于2014年4月16日星期三写道：

**Comment by zizhengtai** [comment]
关于外部库的问题我有空会在README中详细说明，但是我还是不赞同INSTALL部分。

Zizheng Tai zizheng.tai@gmail.com于2014年4月17日星期四写道：

**Comment by Artoria2e5** [comment]
于是我们应该仔细看看IDE编译的时候干了啥

btw，目前还没有类UNIX和UNIX系统编译成功的报告吧。

**Comment by zizhengtai** [comment]
如果算上我自己的话有一例……

Arthur Wang notifications@github.com于2014年4月17日星期四写道：
